neenopal/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('updateblog/<int:id>/', views.updateblog, name='updateblog'),
    path('delete_blog/<int:id>/', views.delete_blog, name='delete_blog'),
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=20)
    createdDate = models.DateField()
    author = models.CharField(max_length=20)
    description = models.TextField()
    isPublished = models.CharField(max_length=10)

blog/forms.py
from tkinter import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _

from .models import Post

class SignUpForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),
        'first_name':forms.TextInput(attrs={'class':'form-control'}),
        'last_name':forms.TextInput(attrs={'class':'form-control'}),
        'email':forms.EmailInput(attrs={'class':'form-control'})}

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label =_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'createdDate', 'author', 'description', 'isPublished']
        labels = {'title':'Title', 'createdDate':'Created Date', 'author': 'Author', 'description':'Description', 'isPublished':'Is Published'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),
        'createdDate':forms.DateInput(attrs={'class':'form-control'}),
        'author':forms.TextInput(attrs={'class':'form-control'}),
        'description':forms.Textarea(attrs={'class':'form-control'}),
        'isPublished':forms.TextInput(attrs={'class':'form-control'})}

blog/views.py
from distutils.log import Log
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignUpForm, LoginForm, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post
from django.contrib.auth.models import Group


# Home view

def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {'posts':posts})

# Dashboard view

def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        return render(request, 'dashboard.html', {'posts':posts, 'full_name':full_name, 'groups':gps})
    else:
        return HttpResponseRedirect('/login/')

# Register view

def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Congratulations!! You have successfully registered to Blog made easy')
            user = form.save()
            group = Group.objects.get(name='Author')
            user.groups.add(group)
    else:
     form = SignUpForm()
    return render(request, 'register.html', {'form':form})

# Login view

def user_login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in Successfully !!')
                    return HttpResponseRedirect('/dashboard/')
        else:
            form = LoginForm()
        return render(request, 'user_login.html', {'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')

# Logout view

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


# Add New Blog
def add_blog(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                createdDate = form.cleaned_data['createdDate']
                author = form.cleaned_data['author']
                description = form.cleaned_data['description']
                isPublished = form.cleaned_data['isPublished']
                pst = Post(title=title, createdDate=createdDate, author=author, description=description, isPublished=isPublished)
                pst.save()
                form = PostForm()
        else:
            form = PostForm()
        return render(request, 'add_blog.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')

# Update Blog
def updateblog(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            form = PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
        else:
            pi = Post.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request, 'updateblog.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')

# delete Blog
def delete_blog(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Post.objects.get(pk=id)
            pi.delete()
        return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

blog/templates/add_blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-cm-10">
    <h3 class="text-white my-5">Add Blog</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>

{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lan="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width",
        initial-scale="1.0">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        <div class="container-fluid bg-dark">
            {% include 'navbar.html' %}
        </div>

        <div class="container">

            <div class="row">
                <div class="col-sm-12">
                    {% block msg %}
                    {% endblock msg %}
                </div>
            </div>

            <div class="row">
                {% block side %}
                {% endblock side %}

                {% block content %}
                {% endblock content %}
            </div>

        </div>


        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/poppper.js' %}"></script>
        <script src="{% static 'js/bootstarp.js' %}"></script>
    </body>
</html>

blog/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block msg %}
    {% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    {% endif %}
{% endblock msg %}


{% block side %}

<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
</div>

{% endblock side %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard</h3>
    <a href="{% url 'add_blog' %}" class="btn btn-success">Add Blog</a>
    <h4 class="text-center alert alert-info mt-3">Show Blogs Information</h4>
        {% if posts %}
            <table class="table table-hover bg-white">
                <thead>
                    <tr class="text-center">
                        <th scope="col" style="width:2%">ID</th>
                        <th scope="col" style="width:8%">Title</th>
                        <th scope="col" style="width:10%">Created Date</th>
                        <th scope="col" style="width:5%">Author</th>
                        <th scope="col" style="width:55%">Blog</th>
                        <th scope="col" style="width:10%">Is Published</th>
                        <th scope="col" style="width:10%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <th scope="row">{{post.id}}</th>
                            <td>{{post.title}}</td>
                            <td>{{post.createdDate}}</td>   
                            <td>{{post.author}}</td> 
                            <td>{{post.description}}</td> 
                            <td>{{post.isPublished}}</td>     
                            <td class="text-center">
                                <a href="{% url 'updateblog' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                                {% if perms.blog.delete_post %}
                                <form action="{% url 'delete_blog' post.id %}" method="post" class="d-inline"> {% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% else %}
            <h4 class="text-center alert alert-warning">No Records Found</h4>
        {% endif %}
</div>
{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Home Page</h3>

    {% for post in posts %}
        <div class="jumbotron jumbotron-fluid jumbo-color">
            <div class="container">
               
                <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
                <h5 class="display-9">{{post.createdDate}}</h5>
                <h5 class="display-9"><i>Author : </i>{{post.author}}</h5>
                <p class="lead my-3"><i>{{post.description}}</i></p>
            
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Bloging is easy now !! </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">logout</a>
            </li>
            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register (New User)</a>
            </li>


            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login/Signin</a>
            </li>
          {% endif %}

         
       
         

    
        </ul>
      </div>
    </div>
  </nav>

blog/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="col-sm-3">
    <h3 class="text-white my-5">Register (new user)</h3>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}}</p>
    {% endfor %}
    {% endif %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
        </div>
        {% endfor %}
        <input type="submit" value="Register" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>

{% endblock content %}

blog/templates/updateblog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-cm-10">
    <h3 class="text-white my-5">Update Blog</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="update" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>

</div>

{% endblock content %}

blog/templates/user_login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="col-sm-5">
    <h3 class="text-white my-5">Login Page</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
        </div>
        {% endfor %}
        <input type="submit" value="Login" class="btn btn-primary my-3">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>

{% endblock content %}